// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTYXxwXT0Fi8qex2LuNzOU7JYCi7KMdc',
    appId: '1:861020086208:web:e70557474be9f4099a3225',
    messagingSenderId: '861020086208',
    projectId: 'mnnitgptauth',
    authDomain: 'mnnitgptauth.firebaseapp.com',
    storageBucket: 'mnnitgptauth.appspot.com',
    measurementId: 'G-D8DLH08KN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvdbrs-mPbVdrQUDsq1zADbvLkgqGNB1o',
    appId: '1:861020086208:android:cf8ef5ed7281abcd9a3225',
    messagingSenderId: '861020086208',
    projectId: 'mnnitgptauth',
    storageBucket: 'mnnitgptauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJh6NPLo5SrBzXFqbJfR_9URDFmZ-9kEQ',
    appId: '1:861020086208:ios:7bbb7ef06ad102649a3225',
    messagingSenderId: '861020086208',
    projectId: 'mnnitgptauth',
    storageBucket: 'mnnitgptauth.appspot.com',
    iosBundleId: 'com.example.mnnitGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJh6NPLo5SrBzXFqbJfR_9URDFmZ-9kEQ',
    appId: '1:861020086208:ios:7bbb7ef06ad102649a3225',
    messagingSenderId: '861020086208',
    projectId: 'mnnitgptauth',
    storageBucket: 'mnnitgptauth.appspot.com',
    iosBundleId: 'com.example.mnnitGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATTYXxwXT0Fi8qex2LuNzOU7JYCi7KMdc',
    appId: '1:861020086208:web:e004dc5d0e6e856a9a3225',
    messagingSenderId: '861020086208',
    projectId: 'mnnitgptauth',
    authDomain: 'mnnitgptauth.firebaseapp.com',
    storageBucket: 'mnnitgptauth.appspot.com',
    measurementId: 'G-RMZSMR7DXC',
  );
}
